### ISSUE TITLE
Bug: Game round ends when not all players distribute cards in time during Merry Christmas

### ISSUE THREAD

**Issue by flaviakim** [soprafs20-group09/frantic-server#1] opened 2021-01-31 20:24 UTC
### Issue description

When the event Merry Christmas happened when playing today and some players took too long to select how they wanted to distribute the cards, the game ended and two players had 0 points while the other two ended up having lots of points.

### Steps to reproduce the issue

I can't verify whether this happens every time. It happened 1/1 times when Merry Christmas happened. This is how it happened:

1. Play colourless cards until Merry Christmas happens.
2. Two players distribute their cards and select enter. (one of the two is not 100% sure, whether they managed to hit enter in time, the other one is sure)
3. Two players only distribute their cards, but don't press enter.

-> Game Round ends, the two players who selected enter have 0 points, the other two have a lot of points (exact number not known anymore).

The two players who hit enter did also distribute cards among each other, so even their cards did not get distributed.

### What's the expected result?

The cards of players who did not manage to distribute their cards in time get distributed randomly and evenly among the other players. The game continues.

### What's the actual result?

The game ended and points have been awarded wrongfully.

**Comment by JaanWilli** [comment] 2021-02-02 16:34
Our general consensus was that whenever someone does not complete their action in time, he should not benefit in any way. In this case, a player who does not hit enter in time has to keep all his cards. This could mean that the opponent can get rid of all cards without getting any new ones, which would then end the round.

Nonetheless, there is an issue with card distribution and I am looking into it.

**Comment by JaanWilli** [comment] 2021-02-16 12:09
While I initially thought there could be a card distribution issue, I was not able to reproduce it. I am therefore going to close this issue for now, please reopen it, should this issue reoccur.

**Closed as completed by JaanWilli** 2021-02-16 12:09 UTC
Labels: bug

**Comment by flaviakim** [comment] 2021-02-24 17:59
Ok I guess I mistook a feature for a bug :)

But I think the time to react to certain events definitely needs to be higher if players are to be punished this harshly for not completing their action in time.
